### ISSUE TITLE
gave en language id but downloads french or spanish srt

### ISSUE THREAD

**Issue by MuVen** [masterwok/open-subtitles-android#2]
Game of Thrones S01E01 and sublanguage id is en

it downloads srt file which is not in english.

**Comment by masterwok** [comment]
Could you please provide the URL created by OpenSubtitlesUrlBuilder?

**Comment by MuVen** [comment]
Any url, language I'd should be eng, not en.

**Comment by MuVen** [comment]
In the sample VLC player are you trying to load subtitles from media title ? Or trying to parse title and extract season episode and then load the subtitles ?

**Comment by masterwok** [comment]
No parsing is done on the title. You can look at the [OpenSubtitlesBuilder](OpenSubtitlesBuilder) class to see how the request URL is built. The [REST endpoint](https://forum.opensubtitles.org/viewtopic.php?f=8&t=16453#p39771) does support season and episode but the builder doesn't have this functionality (it should be fairly easy to add).

I'm still not sure how you're getting "en" as a language identifier. You should be providing the language code to the builder. For example:

```kotlin
val url = OpenSubtitlesUrlBuilder()
        .query("Game of Thrones S01E01")
        .subLanguageId("eng")
        .build()
```

**Comment by masterwok** [comment]
Did you figure this out?

**Comment by MuVen** [comment]
Yes Jonathan Trowbridge. I was able to download English subtitles on giving
eng. It's working great !!!

**Comment by masterwok** [comment]
Thank you, I'm glad you were able to get it working :)

**Comment by MuVen** [comment]
How many languages are supported by opensubtitles ?

Can you drop me link of you dont mind

**Comment by masterwok** [comment]
Open Subtitles exports a list of their languages here: 

[https://www.opensubtitles.org/addons/export_languages.php](https://www.opensubtitles.org/addons/export_languages.php)

I referenced the VLC Android project to help me determine what supported languages to present to users. Maybe this will be of use to you too:

[https://code.videolan.org/videolan/vlc-android/blob/master/vlc-android/res/values/arrays.xml](https://code.videolan.org/videolan/vlc-android/blob/master/vlc-android/res/values/arrays.xml)

**Comment by MuVen** [comment]
Fantastic !!! Thanks for your help

**Comment by MuVen** [comment]
Hi,

I was playing around VLC player android and I saw you contributing
simplevlcplayer in your github. I got a query on VLC android. In the
PlayerControllet.kt can I get the subtitles which are being displayed from
the current track ?

Thanks in advance !!!

**Comment by MuVen** [comment]
I tried searching in the videoplayeractivity. I want to get currently
displayed subtitle cue. Is there any way to get that ?

**Comment by masterwok** [comment]
Hi, sorry I've been busy these past few days. I'll get back to you on this later this evening.

**Comment by masterwok** [comment]
@MuVen I honestly never took the time to get the VLC Android project building. I used it as a reference when building the simple-vlc-player library. I think what you're looking for are called media slaves.

I might be wrong but...

You might be able to use the [SlaveRepository.kt](https://code.videolan.org/videolan/vlc-android/blob/master/vlc-android/src/org/videolan/vlc/repository/SlaveRepository.kt#L49) to get a list of [Slave.kt](https://code.videolan.org/videolan/vlc-android/blob/master/vlc-android/src/org/videolan/vlc/database/models/Slave.kt) instances applied to the media currently playing. If you can, you should be able to get the locations of the subtitles.

It looks like the PlayerController.kt class doesn't expose a method although you could probably easily write one using the private `slaveRepository` field.

Again, I'm not entirely sure on this as I'd have to get the project building and poke around in it for a bit.

I hope that helps some, good luck!
