### ISSUE TITLE
Class members are null in release build

### ISSUE THREAD

**Issue by tstr007** [masterwok/open-subtitles-android#4]
Thanks for this library.
Everything works fine in debug build and when there is no obfuscation via proguard or R8.
In release build with obfuscation , class members are null.
Any ideas?

**Comment by masterwok** [comment]
In an application where I'm using this library I have the following in my **proguard-rules.pro** file:

```gradle
# Open Subtitles Android
-keep class com.masterwok.opensubtitlesandroid.** {*;}
```

The line above seems to work for me in my release builds. Hope that helps!

**Comment by tstr007** [comment]
Thank you. it works. Another solution would be to add @SerializedName from gson lib.

 ` @SerializedName("MatchedBy")
    val MatchedBy: String,
    @SerializedName("IDSubMovieFile")
    val IDSubMovieFile: String,` .....

Thanks again for this library.

**Comment by masterwok** [comment]
Oh nice, thanks for showing me that. 

No problem, I'm glad you found it useful!
